### ISSUE TITLE
Firefox is broken, Chrome and Edge works fine.

### ISSUE THREAD

**Issue by gumbarros** [corejavascript/typeahead.js#257]
Edge:
![image](https://github.com/corejavascript/typeahead.js/assets/52143624/4ebeb5b2-1ee7-4990-98de-22e6601f7db1)

Firefox:
![image](https://github.com/corejavascript/typeahead.js/assets/52143624/859e170f-7ce6-411f-b8ec-3c5bd598143b)

`min-width` workaround just for firefox.
```css
.search-box-menu{
    width: 100%;
    min-width: 18.75rem !important;
}
```

Our typeahead initialization:https://github.com/JJConsulting/JJMasterData/blob/main/src/Web/Scripts/SearchBoxListener.ts

If you want to repro, create a SearchBox in a form at https://www.github.com/jjconsulting/jjmasterdata
